export interface CreateClientDTO {
  code: string;
  name: string;
  mobile?: string;
  email?: string;
  password?: string;
  gstin?: string;
  pan?: string;
  address?: string;
  stateCode?: string;
  city?: string;
  pincode?: string;
  location?: string;
  creditLimit?: number;
  entityType?: 'individual' | 'proprietorship' | 'partnership' | 'pvt_ltd' | 'pub_ltd' | 'llp' | 'trust_ngo' | 'other';
  businessName?: string;
  industrySector?: string;
  incorporationDate?: Date;
  gstStatus?: 'registered' | 'unregistered' | 'exempted';
  financialYearEnd?: 'march_31' | 'december_31' | 'other';
  accountingMethod?: 'cash' | 'accrual';
  estimatedTurnover?: string;
  employeeCount?: string;
  identityProofUrl?: string;
  businessRegistrationUrl?: string;
  taxCardCopyUrl?: string;
  previousYearReturnUrl?: string;
  termsAccepted?: boolean;
  taxId?: string;
  notes?: string;
}

export interface UpdateClientDTO {
  code?: string;
  name?: string;
  mobile?: string;
  email?: string;
  password?: string;
  gstin?: string;
  pan?: string;
  address?: string;
  stateCode?: string;
  city?: string;
  pincode?: string;
  location?: string;
  creditLimit?: number;
  entityType?: any;
  businessName?: string;
  industrySector?: string;
  incorporationDate?: Date;
  gstStatus?: string;
  financialYearEnd?: string;
  accountingMethod?: string;
  estimatedTurnover?: string;
  employeeCount?: string;
  identityProofUrl?: string;
  businessRegistrationUrl?: string;
  taxCardCopyUrl?: string;
  previousYearReturnUrl?: string;
  termsAccepted?: boolean;
  taxId?: string;
  notes?: string;
  isActive?: boolean;
  metadata?: any;
}

export interface ClientResponseDTO {
  id: string;
  code: string;
  name: string;
  isActive: boolean;
  gstin?: string | null;
  pan?: string | null;
  stateCode: string;
  mobile?: string | null;
  email?: string | null;
  address?: string | null;
  city?: string | null;
  pincode?: string | null;
  location?: string | null;
  creditLimit?: number;
  entityType?: string;
  businessName?: string | null;
  industrySector?: string | null;
  incorporationDate?: Date | null;
  gstStatus?: string | null;
  financialYearEnd?: string | null;
  accountingMethod?: string | null;
  estimatedTurnover?: string | null;
  employeeCount?: string | null;
  identityProofUrl?: string | null;
  businessRegistrationUrl?: string | null;
  taxCardCopyUrl?: string | null;
  previousYearReturnUrl?: string | null;
  termsAccepted?: boolean;
  notes?: string | null;
  metadata?: any;
  user: {
    id: string;
    name: string;
    mobile: string;
    isActive: boolean;
  };
  years?: { id: string, year: string, documentCount?: number }[];
  createdAt?: Date;
  updatedAt?: Date;
}
